### ISSUE TITLE
Front-end

### ISSUE THREAD

**Issue by matheusggds** [theandersonn/custom-post-types#2]
O que acha de criarmos uma pasta para por código para o 'front'. 

Algo como consultas com o WP_Query para posts, somente uma base mesmo onde possamos ter uma base mais fácil e pronta do que a própria documentação do WP.

**Comment by theandersonn** [comment]
@matheusggds Uma nova pasta, seria um novo repositório? Se entendi... acho super valido, tenho pensado em como retornar querys complexas do banco e seria uma boa documentar pra facilitar o uso dessas informações.

Fale mais de sua sugestão.

**Comment by matheusggds** [comment]
Então, na verdade eu tinha pensado em uma pasta dentro do próprio repositórios ' custom-post-type '.

Eu desenvolvo plugins e temas para Wordpress, e existem muitas coisas que se repetem, registrar post types, listar posts no front entre MUITAS outras coisas... e seria ótimo um lugar organizado e documentado, para pegar algumas coisas prontas, pelo menos as coisas básicas. 

Mas existem algumas funções interessantes também, assim como as que existem na sua pastas 'functions' que são na verdade "dicas", mas que podem ser muito úteis... e por questão da correria muitas vezes fica mais facil procurar na net um register_taxonomy com os argumentos do que pegar de um projeto anterior.

Se tivéssemos essas coisas aqui, acho que facilitaria muito o processo... não sei se você tambem trabalha com isso, caso sim, acho que seria interessante até porque o repositório/projeto é seu (:

Talvez neste repositório mesmo algo dividido por pastas como:

- Register Posts
- Display/Get posts, and tips
- Wordpress painel functions

Pensei tudo nisso agora, pode ser algo bem melhor elaborado, se é que entendeu meu ponto, podemos transformar este repositório em um banco de dados de código de WP.

**Comment by theandersonn** [comment]
@matheusggds Curti a ideia! Tbm trabalho com desenvolvimento de temas WP.

Acha que esse repositório se encaixar melhor na ideia que vc teve?
https://github.com/theandersonn/wp-snippets

Tenho por habito fazer isso tbm, documentar comandos, preparar pequenos boilerplates e componentes para agilizar o trabalho no dia a dia.

Vamos evoluir a ideia, curti!

**Comment by matheusggds** [comment]
Oloco, era exatamente algo assim que eu tava me referindo, hahaha.

Vou dar uma checada lá e qualquer coisa, vai nos pull-request x)

é nois mano, abraço

**Comment by theandersonn** [comment]
De boa, vlw! 
Sugestões são bem vindas :)
